### ISSUE TITLE
Unclear why check-multi-proj fails 

### ISSUE THREAD

**Issue by alanvgreen** [google/CFU-Playground#276]
The CI check-multi-proj test is failing on https://github.com/google/CFU-Playground/pull/251.

This PR runs multiple copies of nextpnr-nexus.

It looks as though nextpnr-nexus might be failing to find a file?

The exact same commands work for me on my command line, so it's probably a difference between my set up and the CI.

```
Warnings: 2 unique messages, 2 total
End of script. Logfile hash: 7d2dc4b22e, CPU: user 31.26s system 0.20s, MEM: 348.26 MB peak
Yosys 0.9+4303 (git sha1 c88eaea6, clang 10.0.0-4ubuntu1 -fPIC -Os)
Time spent: 18% 1x abc9_exe (7 sec), 16% 18x techmap (6 sec), ...
All seeds failed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', prjoxide/src/bin/prjoxide.rs:57:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "./hps_soc.py", line 284, in <module>
    main()
  File "./hps_soc.py", line 276, in main
    vns = builder.build(**builder_kwargs, run=args.build)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/soc/integration/builder.py", line 310, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/soc/integration/soc.py", line 1127, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/build/lattice/platform.py", line 43, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/build/lattice/oxide.py", line 168, in build
    _run_script(script)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/build/lattice/oxide.py", line 104, in _run_script
    raise OSError("Error occured during Yosys/Nextpnr's script execution.")
OSError: Error occured during Yosys/Nextpnr's script execution.
make[1]: *** [/home/runner/work/CFU-Playground/CFU-Playground/soc/hps.mk:89: build/hps.proj_template_v/gateware/hps_proto2_platform.bit] Error 1
make[1]: Leaving directory '/home/runner/work/CFU-Playground/CFU-Playground/soc'
make: *** [../proj.mk:265: bitstream] Error 2
Error: Process completed with exit code 2.
```

**Comment by tcal-x** [comment]
We found that $(nproc) was 2, less than was expected, causing the parallel nextpnr script to spawn -zero- parallel jobs.
